// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DndApp.Api.Data;

#nullable disable

namespace DndApp.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260430092435_AddCharacterExperienceAndLevelingTables")]
    partial class AddCharacterExperienceAndLevelingTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DndApp.Api.Data.CharacterExperienceEntity", b =>
            {
                b.Property<string>("CharacterId")
                    .HasColumnType("TEXT")
                    .HasMaxLength(64);

                b.Property<int>("CurrentLevel")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasDefaultValue(1);

                b.Property<long>("TotalExperience")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasDefaultValue(0L);

                b.Property<long>("ExperienceForNextLevel")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasDefaultValue(300L);

                b.HasKey("CharacterId");

                b.HasIndex("CurrentLevel");

                b.ToTable("character_experience");
            });

            modelBuilder.Entity("DndApp.Api.Data.CharacterLevelProgressionEntity", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("TEXT")
                    .HasMaxLength(64);

                b.Property<string>("CharacterId")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasMaxLength(64);

                b.Property<int>("Level")
                    .HasColumnType("INTEGER");

                b.Property<long>("ExperienceRequired")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("CharacterId");
                b.HasIndex("Level");

                b.ToTable("character_level_progression");
            });

#pragma warning restore 612, 618
        }
    }
}
