// <auto-generated />
using DndApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DndApp.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417034737_AddRawSourceSchema")]
    partial class AddRawSourceSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("DndApp.Api.Data.ContentSourceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleSystemId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("RuleSystemId");

                    b.ToTable("content_source", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.RuleSystemEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("rule_system", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.SourceBlockEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BlockType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ParseConfidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSectionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceSectionId");

                    b.ToTable("source_block", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.SourceBookEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionTag")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceCode", "VersionTag")
                        .IsUnique();

                    b.ToTable("source_book", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.SourceChapterEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("ChapterOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceBookId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceBookId", "ChapterOrder")
                        .IsUnique();

                    b.ToTable("source_chapter", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.SourceSectionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("EndLine")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectionOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceChapterId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("StartLine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceChapterId", "SectionOrder")
                        .IsUnique();

                    b.ToTable("source_section", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.ContentSourceEntity", b =>
                {
                    b.HasOne("DndApp.Api.Data.RuleSystemEntity", null)
                        .WithMany()
                        .HasForeignKey("RuleSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DndApp.Api.Data.SourceBlockEntity", b =>
                {
                    b.HasOne("DndApp.Api.Data.SourceSectionEntity", null)
                        .WithMany()
                        .HasForeignKey("SourceSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DndApp.Api.Data.SourceChapterEntity", b =>
                {
                    b.HasOne("DndApp.Api.Data.SourceBookEntity", null)
                        .WithMany()
                        .HasForeignKey("SourceBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DndApp.Api.Data.SourceSectionEntity", b =>
                {
                    b.HasOne("DndApp.Api.Data.SourceChapterEntity", null)
                        .WithMany()
                        .HasForeignKey("SourceChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
