// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DndApp.Api.Data;

#nullable disable

namespace DndApp.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429173017_MigrateMissingBackgroundsToCatalogTables")]
    partial class MigrateMissingBackgroundsToCatalogTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DndApp.Api.Data.Entities.AppSettingsEntity", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("TEXT")
                    .HasMaxLength(64);

                b.Property<string>("Value")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("app_settings");
            });

            // Omitted for brevity - just the structure, minimal model
#pragma warning restore 612, 618
        }
    }
}
