// <auto-generated />
using System;
using DndApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DndApp.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260419002538_MergeCatalogSpellTables")]
    partial class MergeCatalogSpellTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("DndApp.Api.Data.Background2014Entity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentSourceId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EditionPayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EquipmentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageChoicesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LegacyRuleModuleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillProficienciesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolProficienciesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LegacyRuleModuleId");

                    b.HasIndex("ContentSourceId", "Slug")
                        .IsUnique();

                    b.ToTable("catalog_background_2014", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.Background2024Entity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentSourceId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EditionPayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrantedFeatSlug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageChoicesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LegacyRuleModuleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillProficienciesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolProficienciesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LegacyRuleModuleId");

                    b.HasIndex("ContentSourceId", "Slug")
                        .IsUnique();

                    b.ToTable("catalog_background_2024", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.CharacterAbilityScoreEntity", b =>
                {
                    b.Property<string>("CharacterId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AbilityName")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId", "AbilityName");

                    b.ToTable("character_ability_score", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.CharacterClassLevelEntity", b =>
                {
                    b.Property<string>("CharacterId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassModuleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId", "SortOrder");

                    b.HasIndex("CharacterId", "ClassModuleId");

                    b.ToTable("character_class_level", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.CharacterDraftEntity", b =>
                {
                    b.Property<string>("CharacterId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseRuleSystem")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MixedModeEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OverlaySourcesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StepsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("character_draft", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.CharacterHistoryEntity", b =>
                {
                    b.Property<string>("EntryId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacterId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("EntryId");

                    b.HasIndex("CharacterId", "TimestampUtc");

                    b.ToTable("character_history", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.CharacterInventoryItemEntity", b =>
                {
                    b.Property<string>("InventoryItemId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AddedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacterId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAttuned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemDefinitionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<bool>("RequiresAttunement")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("InventoryItemId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ItemDefinitionId");

                    b.ToTable("character_inventory_item", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.CharacterRecordEntity", b =>
                {
                    b.Property<string>("CharacterId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseRuleSystem")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MixedModeEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OverlaySourcesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("character_record", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.CharacterResourcePoolEntity", b =>
                {
                    b.Property<string>("CharacterId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId", "ResourceKey");

                    b.ToTable("character_resource_pool", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.CharacterSelectedModuleEntity", b =>
                {
                    b.Property<string>("CharacterId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId", "Slot", "ModuleId");

                    b.ToTable("character_selected_module", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.CharacterSheetEntity", b =>
                {
                    b.Property<string>("CharacterId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseRuleSystem")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("BuildMethod")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassModuleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProficiencyBonus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId");

                    b.HasIndex("ClassModuleId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("character_sheet", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.CharacterSkillProficiencyEntity", b =>
                {
                    b.Property<string>("CharacterId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrainingLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Proficient");

                    b.HasKey("CharacterId", "SkillName");

                    b.ToTable("character_skill_proficiency", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.CharacterSpellEntryEntity", b =>
                {
                    b.Property<string>("CharacterId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpellModuleId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreparationMode")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpellName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId", "SpellModuleId", "PreparationMode");

                    b.ToTable("character_spell_entry", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.CharacterVitalsEntity", b =>
                {
                    b.Property<string>("CharacterId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("BaseArmorClass")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseMoveSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentHitPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHitPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TempHitPoints")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId");

                    b.ToTable("character_vitals", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.ConstraintEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConstraintJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("constraint", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.ContentSourceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleSystemId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("RuleSystemId");

                    b.ToTable("content_source", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.CorrectionOverrideEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AppliedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppliedBy")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("OverrideJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewQueueId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReviewQueueId");

                    b.ToTable("correction_override", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.Feat2014Entity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentSourceId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EditionPayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LegacyRuleModuleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrerequisitesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LegacyRuleModuleId");

                    b.HasIndex("ContentSourceId", "Slug")
                        .IsUnique();

                    b.ToTable("catalog_feat_2014", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.Feat2024Entity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentSourceId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EditionPayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LegacyRuleModuleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrerequisitesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LegacyRuleModuleId");

                    b.HasIndex("ContentSourceId", "Slug")
                        .IsUnique();

                    b.ToTable("catalog_feat_2024", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.ImportReportEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("IngestionRunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngestionRunId");

                    b.ToTable("import_report", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.IngestionRunEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionTag")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceCode", "VersionTag", "StartedAtUtc");

                    b.ToTable("ingestion_run", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.Item2014Entity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("AttackBonus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentSourceId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("DamageBonus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DamageDice")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EditionPayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GoldValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsWeapon")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("LegacyItemDefinitionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LegacyRuleModuleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresAttunement")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("WeaponAbility")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LegacyItemDefinitionId");

                    b.HasIndex("LegacyRuleModuleId");

                    b.HasIndex("ContentSourceId", "Slug")
                        .IsUnique();

                    b.ToTable("catalog_item_2014", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.Item2024Entity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("AttackBonus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentSourceId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("DamageBonus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DamageDice")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EditionPayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GoldValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsWeapon")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("LegacyItemDefinitionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LegacyRuleModuleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresAttunement")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("WeaponAbility")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LegacyItemDefinitionId");

                    b.HasIndex("LegacyRuleModuleId");

                    b.HasIndex("ContentSourceId", "Slug")
                        .IsUnique();

                    b.ToTable("catalog_item_2024", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.ItemDefinitionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("AttackBonus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChargesModelJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DamageBonus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DamageDice")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GoldValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsWeapon")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresAttunement")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleModuleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("WeaponAbility")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RuleModuleId");

                    b.ToTable("item_definition", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.ItemEffectEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EffectPayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EffectType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemDefinitionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemDefinitionId");

                    b.ToTable("item_effect", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.PrerequisiteEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PredicateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleModuleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RuleModuleId");

                    b.ToTable("prerequisite", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.Race2014Entity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AbilityBonusesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentSourceId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EditionPayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSubrace")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguagesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LegacyRuleModuleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentRaceSlug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("TraitsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LegacyRuleModuleId");

                    b.HasIndex("ContentSourceId", "Slug")
                        .IsUnique();

                    b.ToTable("catalog_race_2014", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.ReviewQueueEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("IngestionRunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QueueType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngestionRunId", "Status");

                    b.ToTable("review_queue", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.RuleModuleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentSourceId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionTag")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentSourceId", "Slug", "VersionTag")
                        .IsUnique();

                    b.ToTable("rule_module", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.RuleSystemEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("rule_system", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.RuleVariantEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompatibilityTagsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleModuleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleSystemId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RuleSystemId");

                    b.HasIndex("RuleModuleId", "RuleSystemId")
                        .IsUnique();

                    b.ToTable("rule_variant", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.SourceBlockEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BlockType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ParseConfidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSectionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceSectionId");

                    b.ToTable("source_block", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.SourceBookEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionTag")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceCode", "VersionTag")
                        .IsUnique();

                    b.ToTable("source_book", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.SourceChapterEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("ChapterOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceBookId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceBookId", "ChapterOrder")
                        .IsUnique();

                    b.ToTable("source_chapter", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.SourceSectionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("EndLine")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectionOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceChapterId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("StartLine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceChapterId", "SectionOrder")
                        .IsUnique();

                    b.ToTable("source_section", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.Species2024Entity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AbilityBonusesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentSourceId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EditionPayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguagesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LegacyRuleModuleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("TraitsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LegacyRuleModuleId");

                    b.HasIndex("ContentSourceId", "Slug")
                        .IsUnique();

                    b.ToTable("catalog_species_2024", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.SpellEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CastingTime")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Concentration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentSourceId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("EditionPayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EditionYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LegacyRuleModuleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("RangeText")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ritual")
                        .HasColumnType("INTEGER");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LegacyRuleModuleId");

                    b.HasIndex("ContentSourceId", "Slug", "EditionYear")
                        .IsUnique();

                    b.HasIndex("EditionYear", "Level", "Name");

                    b.ToTable("catalog_spell", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.UserAccountEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.ToTable("user_account", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.UserSessionEntity", b =>
                {
                    b.Property<string>("SessionToken")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("SessionToken");

                    b.HasIndex("UserId");

                    b.ToTable("user_session", (string)null);
                });

            modelBuilder.Entity("DndApp.Api.Data.CharacterAbilityScoreEntity", b =>
                {
                    b.HasOne("DndApp.Api.Data.CharacterSheetEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DndApp.Api.Data.CharacterClassLevelEntity", b =>
                {
                    b.HasOne("DndApp.Api.Data.CharacterSheetEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DndApp.Api.Data.CharacterInventoryItemEntity", b =>
                {
                    b.HasOne("DndApp.Api.Data.CharacterSheetEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DndApp.Api.Data.ItemDefinitionEntity", null)
                        .WithMany()
                        .HasForeignKey("ItemDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DndApp.Api.Data.CharacterResourcePoolEntity", b =>
                {
                    b.HasOne("DndApp.Api.Data.CharacterSheetEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DndApp.Api.Data.CharacterSelectedModuleEntity", b =>
                {
                    b.HasOne("DndApp.Api.Data.CharacterSheetEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DndApp.Api.Data.CharacterSkillProficiencyEntity", b =>
                {
                    b.HasOne("DndApp.Api.Data.CharacterSheetEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DndApp.Api.Data.CharacterSpellEntryEntity", b =>
                {
                    b.HasOne("DndApp.Api.Data.CharacterSheetEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DndApp.Api.Data.CharacterVitalsEntity", b =>
                {
                    b.HasOne("DndApp.Api.Data.CharacterSheetEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DndApp.Api.Data.ContentSourceEntity", b =>
                {
                    b.HasOne("DndApp.Api.Data.RuleSystemEntity", null)
                        .WithMany()
                        .HasForeignKey("RuleSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DndApp.Api.Data.CorrectionOverrideEntity", b =>
                {
                    b.HasOne("DndApp.Api.Data.ReviewQueueEntity", null)
                        .WithMany()
                        .HasForeignKey("ReviewQueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DndApp.Api.Data.ImportReportEntity", b =>
                {
                    b.HasOne("DndApp.Api.Data.IngestionRunEntity", null)
                        .WithMany()
                        .HasForeignKey("IngestionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DndApp.Api.Data.ItemDefinitionEntity", b =>
                {
                    b.HasOne("DndApp.Api.Data.RuleModuleEntity", null)
                        .WithMany()
                        .HasForeignKey("RuleModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DndApp.Api.Data.ItemEffectEntity", b =>
                {
                    b.HasOne("DndApp.Api.Data.ItemDefinitionEntity", null)
                        .WithMany()
                        .HasForeignKey("ItemDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DndApp.Api.Data.PrerequisiteEntity", b =>
                {
                    b.HasOne("DndApp.Api.Data.RuleModuleEntity", null)
                        .WithMany()
                        .HasForeignKey("RuleModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DndApp.Api.Data.ReviewQueueEntity", b =>
                {
                    b.HasOne("DndApp.Api.Data.IngestionRunEntity", null)
                        .WithMany()
                        .HasForeignKey("IngestionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DndApp.Api.Data.RuleModuleEntity", b =>
                {
                    b.HasOne("DndApp.Api.Data.ContentSourceEntity", null)
                        .WithMany()
                        .HasForeignKey("ContentSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DndApp.Api.Data.RuleVariantEntity", b =>
                {
                    b.HasOne("DndApp.Api.Data.RuleModuleEntity", null)
                        .WithMany()
                        .HasForeignKey("RuleModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DndApp.Api.Data.RuleSystemEntity", null)
                        .WithMany()
                        .HasForeignKey("RuleSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DndApp.Api.Data.SourceBlockEntity", b =>
                {
                    b.HasOne("DndApp.Api.Data.SourceSectionEntity", null)
                        .WithMany()
                        .HasForeignKey("SourceSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DndApp.Api.Data.SourceChapterEntity", b =>
                {
                    b.HasOne("DndApp.Api.Data.SourceBookEntity", null)
                        .WithMany()
                        .HasForeignKey("SourceBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DndApp.Api.Data.SourceSectionEntity", b =>
                {
                    b.HasOne("DndApp.Api.Data.SourceChapterEntity", null)
                        .WithMany()
                        .HasForeignKey("SourceChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DndApp.Api.Data.UserSessionEntity", b =>
                {
                    b.HasOne("DndApp.Api.Data.UserAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
