// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DndApp.Api.Data;

#nullable disable

namespace DndApp.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429173545_AddCharacterDisplayOrder")]
    partial class AddCharacterDisplayOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DndApp.Api.Data.Entities.CharacterRecordEntity", b =>
            {
                b.Property<string>("CharacterId")
                    .HasColumnType("TEXT");

                b.Property<int>("DisplayOrder")
                    .HasColumnType("INTEGER");

                b.ToTable("character_record");
            });

#pragma warning restore 612, 618
        }
    }
}
