// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DndApp.Api.Data;

#nullable disable

namespace DndApp.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429180046_AddSkillProficiencySourceTable")]
    partial class AddSkillProficiencySourceTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DndApp.Api.Data.SkillProficiencySourceEntity", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("TEXT")
                    .HasMaxLength(64);

                b.Property<string>("SourceType")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasMaxLength(40);

                b.Property<string>("SkillName")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasMaxLength(80);

                b.Property<bool>("IsExpertise")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasDefaultValue(false);

                b.HasKey("Id");

                b.HasIndex("Edition");
                b.HasIndex("SkillName");
                b.HasIndex("SourceId");
                b.HasIndex("SourceType");

                b.ToTable("skill_proficiency_source");
            });

#pragma warning restore 612, 618
        }
    }
}
