// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DndApp.Api.Data;

#nullable disable

namespace DndApp.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429180124_SeedClassSkillProficiencies")]
    partial class SeedClassSkillProficiencies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DndApp.Api.Data.SkillProficiencySourceEntity", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("TEXT")
                    .HasMaxLength(64);

                b.Property<string>("ChoiceGroup")
                    .HasColumnType("TEXT")
                    .HasMaxLength(120);

                b.Property<string>("Edition")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasMaxLength(10);

                b.Property<bool>("IsChoice")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsExpertise")
                    .HasColumnType("INTEGER")
                    .HasDefaultValue(false);

                b.Property<string>("SkillName")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasMaxLength(80);

                b.Property<string>("SourceId")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasMaxLength(64);

                b.Property<string>("SourceName")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasMaxLength(300);

                b.Property<string>("SourceType")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasMaxLength(40);

                b.HasKey("Id");

                b.ToTable("skill_proficiency_source");
            });

#pragma warning restore 612, 618
        }
    }
}
